# Generated by Django 6.0.2 on 2026-03-31 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0019_add_psa_ticket_and_alerts'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='alert_before_hours',
            field=models.PositiveIntegerField(default=24, help_text='Send an alert this many hours before the due date'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='alert_email',
            field=models.BooleanField(default=True, help_text='Send email alerts for this task'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='alert_sms',
            field=models.BooleanField(default=False, help_text='Send SMS alerts for this task'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='last_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='psa_ticket',
            field=models.ForeignKey(blank=True, help_text='Linked PSA/helpdesk ticket (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_tasks', to='integrations.psaticket'),
        ),
    ]
