# Generated by Django 6.0.2 on 2026-04-11 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_inventory_scheduling_flags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='task_type',
            field=models.CharField(choices=[('cleanup_stuck_scans', 'Cleanup Stuck Security Scans'), ('domain_expiry_check', 'Domain Expiry Check'), ('equipment_catalog_update', 'Equipment Catalog Update'), ('password_breach_scan', 'Password Breach Scanning'), ('psa_sync', 'PSA Synchronization'), ('rmm_sync', 'RMM Synchronization'), ('scheduling_alerts', 'Scheduled Task Alerts'), ('security_scan', 'Automated Security Scan'), ('ssl_expiry_check', 'SSL Certificate Expiry Check'), ('update_check', 'System Update Check'), ('website_monitoring', 'Website Monitoring Checks')], max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='SupportRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('application', 'Application'), ('network', 'Network'), ('customer', 'Customer / Users'), ('hardware', 'Hardware'), ('overall', 'Overall')], max_length=20)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 'Low'), (2, 'Moderate'), (3, 'Elevated'), (4, 'High'), (5, 'Critical')])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_ratings', to='core.organization')),
                ('rated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_ratings',
                'ordering': ['category'],
                'unique_together': {('organization', 'category')},
            },
        ),
    ]
