# Generated by Django 6.0.2 on 2026-04-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_support_ratings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('areas_of_interest', models.TextField(blank=True, help_text='Comma-separated area keys')),
                ('description', models.TextField(blank=True, help_text='Tell us about your situation')),
                ('best_time', models.CharField(blank=True, help_text='Best time to reach you', max_length=100)),
                ('heard_from', models.CharField(blank=True, help_text='How did you hear about us?', max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
            ],
            options={
                'db_table': 'consult_requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
