# Generated by Django 6.0.2 on 2026-04-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_consult_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='asset_age_critical_years',
            field=models.PositiveIntegerField(default=5, help_text='Age (years) at which to show a red critical warning for assets without a lifespan set'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='asset_age_warning_years',
            field=models.PositiveIntegerField(default=3, help_text='Age (years) at which to show a yellow warning for assets without a lifespan set'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='asset_age_warnings_enabled',
            field=models.BooleanField(default=False, help_text='Show warnings when assets approach or exceed their age threshold'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='dell_api_key',
            field=models.CharField(blank=True, help_text='Dell TechDirect API key for warranty lookups', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='firmware_checks_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic firmware update checks for network devices (Ubiquiti, TP-Link, Grandstream, etc.)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='hp_client_id',
            field=models.CharField(blank=True, help_text='HP API client ID for warranty lookups', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='hp_client_secret',
            field=models.CharField(blank=True, help_text='HP API client secret for warranty lookups', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='lenovo_client_id',
            field=models.CharField(blank=True, help_text='Lenovo warranty API client ID', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='lenovo_client_secret',
            field=models.CharField(blank=True, help_text='Lenovo warranty API client secret', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='warranty_checks_enabled',
            field=models.BooleanField(default=False, help_text='Enable warranty expiry lookups for PCs and servers via vendor APIs (Dell, HP, Lenovo)'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='task_type',
            field=models.CharField(choices=[('asset_age_check', 'Asset Age Warning Check'), ('cleanup_stuck_scans', 'Cleanup Stuck Security Scans'), ('domain_expiry_check', 'Domain Expiry Check'), ('equipment_catalog_update', 'Equipment Catalog Update'), ('firmware_check', 'Firmware Update Check'), ('password_breach_scan', 'Password Breach Scanning'), ('psa_sync', 'PSA Synchronization'), ('rmm_sync', 'RMM Synchronization'), ('scheduling_alerts', 'Scheduled Task Alerts'), ('security_scan', 'Automated Security Scan'), ('ssl_expiry_check', 'SSL Certificate Expiry Check'), ('update_check', 'System Update Check'), ('warranty_check', 'Warranty Expiry Check'), ('website_monitoring', 'Website Monitoring Checks')], max_length=50, unique=True),
        ),
    ]
