# Generated by Django 6.0.2 on 2026-02-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_asset_lifespan_reminder_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='cpu',
            field=models.CharField(blank=True, help_text='Processor (e.g., Intel Xeon E5-2680 v4)', max_length=200),
        ),
        migrations.AddField(
            model_name='asset',
            name='os_name',
            field=models.CharField(blank=True, help_text='Operating system (e.g., Windows Server 2022, Ubuntu 22.04, Cisco IOS)', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='os_version',
            field=models.CharField(blank=True, help_text='OS version or build number', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='ram_gb',
            field=models.PositiveIntegerField(blank=True, help_text='RAM in GB', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='storage',
            field=models.CharField(blank=True, help_text='Storage configuration (e.g., 2× 1TB SSD RAID-1)', max_length=200),
        ),
    ]
