# Generated by Django 6.0.2 on 2026-02-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_add_os_and_hardware_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='needs_reorder',
            field=models.BooleanField(default=False, help_text='Flag asset as needing physical reorder/replacement'),
        ),
    ]
