# Generated by Django 6.0.2 on 2026-03-08 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_asset_needs_reorder'),
        ('docs', '0012_add_system_package_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='profile_document',
            field=models.ForeignKey(blank=True, help_text='Auto-generated profile document for this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiled_assets', to='docs.document'),
        ),
    ]
