# Generated by Django 6.0.2 on 2026-04-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_contact_ratings_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='firmware_checked_at',
            field=models.DateTimeField(blank=True, help_text='When firmware was last checked', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='firmware_latest',
            field=models.CharField(blank=True, help_text='Latest available firmware version (populated by scheduler)', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='firmware_version',
            field=models.CharField(blank=True, help_text='Currently installed firmware version', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_checked_at',
            field=models.DateTimeField(blank=True, help_text='When warranty was last checked via vendor API', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_expiry',
            field=models.DateField(blank=True, help_text='Warranty or support contract expiry date', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_status',
            field=models.CharField(blank=True, help_text='Warranty status description (e.g. Active, Expired, ProSupport)', max_length=100),
        ),
    ]
