# Generated by Django 6.0.2 on 2026-04-12 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_update_locale_en_to_en_us'),
        ('core', '0039_asset_health_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_organization',
            field=models.ForeignKey(blank=True, help_text='Default organization to load on login', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.organization'),
        ),
    ]
