# Generated by Django 6.0.2 on 2026-02-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_attachment_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='entity_type',
            field=models.CharField(choices=[('asset', 'Asset'), ('document', 'Document'), ('password', 'Password'), ('contact', 'Contact'), ('vendor', 'Vendor'), ('equipment_model', 'Equipment Model'), ('vehicle', 'Vehicle')], max_length=50),
        ),
    ]
