# Generated by Django 6.0.2 on 2026-02-25 03:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicleinventoryitem_reorder_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Shop or service center name', max_length=200)),
                ('contact_name', models.CharField(blank=True, help_text='Primary contact person', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('service_types', models.TextField(blank=True, help_text='Types of service this provider offers (e.g., Oil change, Tires, Brakes)')),
                ('is_preferred', models.BooleanField(default=False, help_text='Mark as preferred/primary shop for this vehicle')),
                ('notes', models.TextField(blank=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_providers', to='vehicles.servicevehicle')),
            ],
            options={
                'db_table': 'vehicle_service_providers',
                'ordering': ['-is_preferred', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g., Oil Change, Tire Rotation', max_length=200)),
                ('service_type', models.CharField(choices=[('oil_change', 'Oil Change'), ('tire_rotation', 'Tire Rotation'), ('brake_service', 'Brake Service'), ('inspection', 'Inspection'), ('tune_up', 'Tune-up'), ('transmission', 'Transmission Service'), ('coolant', 'Coolant Service'), ('battery', 'Battery Replacement'), ('repair', 'Repair'), ('other', 'Other')], default='other', max_length=50)),
                ('interval_miles', models.IntegerField(blank=True, help_text='Trigger alert every X miles (e.g., 5000 for oil change)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('interval_days', models.IntegerField(blank=True, help_text='Trigger alert every X days (e.g., 90 for 3-month service)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('warning_miles', models.IntegerField(default=500, help_text='Alert this many miles before the service is due', validators=[django.core.validators.MinValueValidator(0)])),
                ('warning_days', models.IntegerField(default=7, help_text='Alert this many days before the service is due', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_service_mileage', models.IntegerField(blank=True, help_text='Odometer reading at last service', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_service_date', models.DateField(blank=True, help_text='Date of last service', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_schedules', to='vehicles.servicevehicle')),
            ],
            options={
                'db_table': 'vehicle_service_schedules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleServiceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_mileage', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('completed', 'Completed — Service Done')], default='pending', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement_notes', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_service_alerts', to=settings.AUTH_USER_MODEL)),
                ('service_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_alert', to='vehicles.vehiclemaintenancerecord')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_alerts', to='vehicles.servicevehicle')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='vehicles.vehicleserviceschedule')),
            ],
            options={
                'db_table': 'vehicle_service_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vehicle', 'status'], name='vehicle_ser_vehicle_cd190c_idx'), models.Index(fields=['status'], name='vehicle_ser_status_0b4346_idx')],
            },
        ),
    ]
