# Generated by Django 6.0.2 on 2026-03-04 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_servicevehicle_diagram_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Item name (e.g., 'CAT6 Cable', 'RJ45 Connectors')", max_length=200)),
                ('category', models.CharField(blank=True, help_text='Category (Cables, Tools, Hardware, Supplies, etc.)', max_length=100)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (ea, ft, box, etc.)', max_length=50)),
                ('min_quantity', models.IntegerField(default=0, help_text='Minimum quantity alert threshold', validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_quantity', models.IntegerField(default=0, help_text='How many to order when restocking', validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit', max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('location_in_shop', models.CharField(blank=True, help_text="Where stored in shop (e.g., 'Shelf A-3', 'Cabinet 2')", max_length=200)),
                ('qr_code', models.CharField(blank=True, max_length=200)),
                ('reorder_link', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'vehicle_shop_inventory',
                'ordering': ['category', 'name'],
            },
        ),
    ]
